const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pollRunner', {
  status: () => ipcRenderer.invoke('bot:status'),
  saveConfig: (config) => ipcRenderer.invoke('bot:save-config', config),
  saveAppSettings: (settings) => ipcRenderer.invoke('app:save-settings', settings),
  start: () => ipcRenderer.invoke('bot:start'),
  stop: () => ipcRenderer.invoke('bot:stop'),
  pause: () => ipcRenderer.invoke('bot:pause'),
  resume: () => ipcRenderer.invoke('bot:resume'),
  onUpdate: (callback) => ipcRenderer.on('bot:update', (_event, data) => callback(data)),
  productsStatus: () => ipcRenderer.invoke('products:status'),
  saveAlertConfig: (config) => ipcRenderer.invoke('products:save-alert-config', config),
  testAlert: () => ipcRenderer.invoke('products:test-alert'),
  addProduct: (product) => ipcRenderer.invoke('products:add', product),
  updateProduct: (id, product) => ipcRenderer.invoke('products:update', id, product),
  removeProduct: (id) => ipcRenderer.invoke('products:remove', id),
  openScreenshot: (filePath) => ipcRenderer.invoke('products:open-screenshot', filePath),
  setProductEnabled: (id, enabled) => ipcRenderer.invoke('products:set-enabled', id, enabled),
  resumeAllProducts: () => ipcRenderer.invoke('products:resume-all'),
  exportProducts: () => ipcRenderer.invoke('products:export'),
  importProducts: () => ipcRenderer.invoke('products:import'),
  startProducts: () => ipcRenderer.invoke('products:start'),
  stopProducts: () => ipcRenderer.invoke('products:stop'),
  checkoutProduct: (id) => ipcRenderer.invoke('products:checkout', id),
  resumeProduct: (id) => ipcRenderer.invoke('products:resume', id),
  onProductsUpdate: (callback) => ipcRenderer.on('products:update', (_event, data) => callback(data)),
  onAlert: (callback) => ipcRenderer.on('products:play-alert', (_event, data) => callback(data)),
});
